// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  base: {
    accordion: {
      name: "accordion",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/accordion.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/accordion")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "accordion"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/accordion",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/accordion-example.tsx",
          api: "https://base-ui.com/react/components/accordion.md",
        },
      },
    },
    alert: {
      name: "alert",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/alert.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/alert")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/alert",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/alert-example.tsx",
        },
      },
    },
    "alert-dialog": {
      name: "alert-dialog",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/alert-dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/alert-dialog")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "alert-dialog"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/alert-dialog",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/alert-dialog-example.tsx",
          api: "https://base-ui.com/react/components/alert-dialog.md",
        },
      },
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/aspect-ratio.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/aspect-ratio")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "aspect-ratio"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/aspect-ratio",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/aspect-ratio-example.tsx",
        },
      },
    },
    avatar: {
      name: "avatar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/avatar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/avatar")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "avatar"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/avatar",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/avatar-example.tsx",
          api: "https://base-ui.com/react/components/avatar.md",
        },
      },
    },
    badge: {
      name: "badge",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/badge.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/badge")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "badge"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/badge",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/badge-example.tsx",
        },
      },
    },
    breadcrumb: {
      name: "breadcrumb",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/breadcrumb.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/breadcrumb")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "breadcrumb"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/breadcrumb",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/breadcrumb-example.tsx",
        },
      },
    },
    button: {
      name: "button",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/button.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/button")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "button"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/button",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/button-example.tsx",
        },
      },
    },
    "button-group": {
      name: "button-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["separator"],
      files: [
        {
          path: "styles/base/ui/button-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/button-group")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "button-group"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/button-group",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/button-group-example.tsx",
        },
      },
    },
    calendar: {
      name: "calendar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/calendar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/calendar")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "calendar"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/calendar",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/calendar-example.tsx",
          api: "https://react-day-picker.js.org",
        },
      },
    },
    "date-picker": {
      name: "date-picker",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "calendar", "popover"],
      files: [
        {
          path: "styles/base/ui/date-picker.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/date-picker")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "date-picker"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/date-picker",
          api: "https://react-spectrum.adobe.com/react-aria/DatePicker.html",
        },
      },
    },
    card: {
      name: "card",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/card.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/card")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "card"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/card",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/card-example.tsx",
        },
      },
    },
    carousel: {
      name: "carousel",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/carousel.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/carousel")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "carousel"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/carousel",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/carousel-example.tsx",
          api: "https://www.embla-carousel.com/get-started/react",
        },
      },
    },
    chart: {
      name: "chart",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["card"],
      files: [
        {
          path: "styles/base/ui/chart.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/chart")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "chart"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/chart",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/chart-example.tsx",
        },
      },
    },
    checkbox: {
      name: "checkbox",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/checkbox.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/checkbox")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "checkbox"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/checkbox",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/checkbox-example.tsx",
          api: "https://base-ui.com/react/components/checkbox.md",
        },
      },
    },
    collapsible: {
      name: "collapsible",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/collapsible.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/collapsible")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "collapsible"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/collapsible",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/collapsible-example.tsx",
          api: "https://base-ui.com/react/components/collapsible.md",
        },
      },
    },
    "color-field": {
      name: "color-field",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/color-field.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/color-field")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "color-field"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          api: "https://react-spectrum.adobe.com/react-aria/ColorField.html",
        },
      },
    },
    "color-picker": {
      name: "color-picker",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/color-picker.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/color-picker")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "color-picker"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          api: "https://react-spectrum.adobe.com/react-aria/ColorPicker.html",
        },
      },
    },
    combobox: {
      name: "combobox",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "input-group"],
      files: [
        {
          path: "styles/base/ui/combobox.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/combobox")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "combobox"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/combobox",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/combobox-example.tsx",
          api: "https://base-ui.com/react/components/combobox.md",
        },
      },
    },
    command: {
      name: "command",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog", "input-group"],
      files: [
        {
          path: "styles/base/ui/command.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/command")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "command"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/command",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/command-example.tsx",
          api: "https://github.com/dip/cmdk",
        },
      },
    },
    "context-menu": {
      name: "context-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/context-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/context-menu")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "context-menu"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/context-menu",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/context-menu-example.tsx",
          api: "https://base-ui.com/react/components/context-menu.md",
        },
      },
    },
    dialog: {
      name: "dialog",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/dialog")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "dialog"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/dialog",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/dialog-example.tsx",
          api: "https://base-ui.com/react/components/dialog.md",
        },
      },
    },
    drawer: {
      name: "drawer",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/drawer.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/drawer")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "drawer"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/drawer",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/drawer-example.tsx",
          api: "https://vaul.emilkowal.ski/getting-started",
        },
      },
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/dropdown-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/dropdown-menu")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "dropdown-menu"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/dropdown-menu",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/dropdown-menu-example.tsx",
          api: "https://base-ui.com/react/components/menu.md",
        },
      },
    },
    empty: {
      name: "empty",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/empty.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/empty")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "empty"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/empty",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/empty-example.tsx",
        },
      },
    },
    field: {
      name: "field",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["label", "separator"],
      files: [
        {
          path: "styles/base/ui/field.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/field")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "field"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/field",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/field-example.tsx",
        },
      },
    },
    "hover-card": {
      name: "hover-card",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/hover-card.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/hover-card")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "hover-card"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/hover-card",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/hover-card-example.tsx",
          api: "https://base-ui.com/react/components/hover-card.md",
        },
      },
    },
    input: {
      name: "input",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/input.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/input")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "input"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/input",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/input-example.tsx",
        },
      },
    },
    "input-group": {
      name: "input-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "input", "textarea"],
      files: [
        {
          path: "styles/base/ui/input-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/input-group")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "input-group"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/input-group",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/input-group-example.tsx",
        },
      },
    },
    "input-otp": {
      name: "input-otp",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/input-otp.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/input-otp")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "input-otp"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/input-otp",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/input-otp-example.tsx",
          api: "https://input-otp.rodz.dev",
        },
      },
    },
    item: {
      name: "item",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["separator"],
      files: [
        {
          path: "styles/base/ui/item.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/item")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "item"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/item",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/item-example.tsx",
        },
      },
    },
    label: {
      name: "label",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/label.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/label")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "label"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/label",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/label-example.tsx",
          api: "https://base-ui.com/react/components/label.md",
        },
      },
    },
    menubar: {
      name: "menubar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dropdown-menu"],
      files: [
        {
          path: "styles/base/ui/menubar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/menubar")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "menubar"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/menubar",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/menubar-example.tsx",
          api: "https://base-ui.com/react/components/menubar.md",
        },
      },
    },
    "navigation-menu": {
      name: "navigation-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/navigation-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/navigation-menu")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "navigation-menu"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/navigation-menu",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/navigation-menu-example.tsx",
          api: "https://base-ui.com/react/components/navigation-menu.md",
        },
      },
    },
    pagination: {
      name: "pagination",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/pagination.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/pagination")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "pagination"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/pagination",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/pagination-example.tsx",
        },
      },
    },
    popover: {
      name: "popover",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/popover.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/popover")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "popover"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/popover",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/popover-example.tsx",
          api: "https://base-ui.com/react/components/popover.md",
        },
      },
    },
    progress: {
      name: "progress",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/progress.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/progress")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "progress"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/progress",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/progress-example.tsx",
          api: "https://base-ui.com/react/components/progress.md",
        },
      },
    },
    "radio-group": {
      name: "radio-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/radio-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/radio-group")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "radio-group"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/radio-group",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/radio-group-example.tsx",
          api: "https://base-ui.com/react/components/radio-group.md",
        },
      },
    },
    resizable: {
      name: "resizable",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/resizable.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/resizable")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "resizable"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/resizable",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/resizable-example.tsx",
          api: "https://github.com/bvaughn/react-resizable-panels",
        },
      },
    },
    "scroll-area": {
      name: "scroll-area",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/scroll-area.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/scroll-area")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "scroll-area"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/scroll-area",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/scroll-area-example.tsx",
          api: "https://base-ui.com/react/components/scroll-area.md",
        },
      },
    },
    select: {
      name: "select",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/select.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/select")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "select"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/select",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/select-example.tsx",
          api: "https://base-ui.com/react/components/select.md",
        },
      },
    },
    separator: {
      name: "separator",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/separator.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/separator")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "separator"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/separator",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/separator-example.tsx",
          api: "https://base-ui.com/react/components/separator.md",
        },
      },
    },
    sheet: {
      name: "sheet",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "styles/base/ui/sheet.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/sheet")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sheet"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/sheet",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/sheet-example.tsx",
          api: "https://base-ui.com/react/components/dialog.md",
        },
      },
    },
    sidebar: {
      name: "sidebar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: [
        "button",
        "input",
        "separator",
        "sheet",
        "skeleton",
        "tooltip",
        "use-mobile",
      ],
      files: [
        {
          path: "styles/base/ui/sidebar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/sidebar")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sidebar"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/sidebar",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/sidebar-example.tsx",
        },
      },
    },
    skeleton: {
      name: "skeleton",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/skeleton.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/skeleton")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "skeleton"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/skeleton",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/skeleton-example.tsx",
        },
      },
    },
    slider: {
      name: "slider",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/slider.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/slider")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "slider"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/slider",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/slider-example.tsx",
          api: "https://base-ui.com/react/components/slider.md",
        },
      },
    },
    sonner: {
      name: "sonner",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/sonner.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/sonner")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sonner"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/sonner",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/sonner-example.tsx",
          api: "https://sonner.emilkowal.ski",
        },
      },
    },
    spinner: {
      name: "spinner",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/spinner.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/spinner")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "spinner"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/spinner",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/spinner-example.tsx",
        },
      },
    },
    switch: {
      name: "switch",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/switch.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/switch")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "switch"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/switch",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/switch-example.tsx",
          api: "https://base-ui.com/react/components/switch.md",
        },
      },
    },
    table: {
      name: "table",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/table.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/table")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "table"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/table",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/table-example.tsx",
        },
      },
    },
    tabs: {
      name: "tabs",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/tabs.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/tabs")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tabs"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/tabs",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/tabs-example.tsx",
          api: "https://base-ui.com/react/components/tabs.md",
        },
      },
    },
    textarea: {
      name: "textarea",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/textarea.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/textarea")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "textarea"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/textarea",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/textarea-example.tsx",
        },
      },
    },
    toggle: {
      name: "toggle",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/toggle.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/toggle")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "toggle"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/toggle",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/toggle-example.tsx",
          api: "https://base-ui.com/react/components/toggle.md",
        },
      },
    },
    "toggle-group": {
      name: "toggle-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "styles/base/ui/toggle-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/toggle-group")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "toggle-group"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/toggle-group",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/toggle-group-example.tsx",
          api: "https://base-ui.com/react/components/toggle-group.md",
        },
      },
    },
    tooltip: {
      name: "tooltip",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/tooltip.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/tooltip")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "tooltip"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/tooltip",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/tooltip-example.tsx",
          api: "https://base-ui.com/react/components/tooltip.md",
        },
      },
    },
    "time-field": {
      name: "time-field",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/time-field.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/time-field")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "time-field"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/time-field",
          api: "https://react-spectrum.adobe.com/react-aria/TimeField.html",
        },
      },
    },
    kbd: {
      name: "kbd",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/kbd.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/kbd")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "kbd"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/kbd",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/kbd-example.tsx",
        },
      },
    },
    "native-select": {
      name: "native-select",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/native-select.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/native-select")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "native-select"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/native-select",
          examples:
            "https://ui.shadcn.com/code/apps/v4/registry/bases/base/examples/native-select-example.tsx",
        },
      },
    },
    direction: {
      name: "direction",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/direction.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/direction")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "direction"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/direction",
          api: "https://base-ui.com/react/utils/direction-provider.md",
        },
      },
    },
    "qr-code": {
      name: "qr-code",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/qr-code.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/qr-code")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "qr-code"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: { docs: "https://ui.shadcn.com/docs/components/base/qr-code" },
      },
    },
    "number-field": {
      name: "number-field",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["label"],
      files: [
        {
          path: "styles/base/ui/number-field.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/number-field")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "number-field"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/number-field",
          api: "https://base-ui.com/react/components/number-field.md",
        },
      },
    },
    sortable: {
      name: "sortable",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "styles/base/ui/sortable.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/styles/base/ui/sortable")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "sortable"
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: {
        links: {
          docs: "https://ui.shadcn.com/docs/components/base/sortable",
          api: "https://dndkit.com",
        },
      },
    },
  },
}
